<?php
use App\Models\InternalNotification;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;


/**
 * Create a notification for a user.
 *
 * @param int $userId The ID of the user to notify.
 * @param string $title The title of the notification.
 * @param string $body The body/message of the notification.
 * @param string|null $link Optional link for the notification.
 * @return void
 */

 if (!function_exists('assignPermissionsToRole')) {
    /**
     * Assign permissions to a role based on user type.
     *
     * @param Role $role
     * @param string $userType
     * @return void
     */
    function assignPermissionsToRole(Role $role, string $userType)
    {
        // Define default permissions for each user type
        $permissions = [
            'super admin' => [
                'show business intelligence',
                'show risk management',
                'show mrm',
                'raise query',
                'assign query',
                'view item supply',
                'director approve SRN',
                'liaison approve SRN',
                'bursar approve SRN',
                'store approve SRN',
                'request SRN',
                'view SRN',
                'print SIV',
                'special duty approve',
                'report view',
                'liaison approve',
                'unit head approve',
                'director approve',
                'dg approve',
                'bursar approve',
                'pv approve',
                'audit approve',
                'final account approve',
                'create folder',
                'view department folders',
                'view unit folders',
                'rename folder',
                'delete folder',
                'create document',
                'view department documents',
                'view unit documents',
                'share document',
                'archive document',
                'rename document',
                'delete document',
                'manage attendance report',
                'show bursary menu',
                'show account overview',
                'show reports',
                'show banking',
                'show voucher',
                'show purchases',
                'show double entry',
                'show budget planner',
                'show financial goal',
                'show accounting setup',
                'show print setup',
                'show chart of account',
                'show journal',
                'show ledger',
                'show balance sheet',
                'show profit and loss',
                'show trial balance',
                'approve as liaison officer',
                'manage requisition',
                'request purchase requisition',
                'manage contract',
                'view contract',
                'recommend payment',
                'view contract value',
                'comment on contract',
                'view payment history',
                'print voucher',
                'approve payment',
                'bursar approval',
                'raise contract voucher',
                'audit approval',
                'make payment',
                'view recommended payment',
                'set budget',
                'manage budget',
                'approve budget',
                'reject budget',
                'view budget',
                'edit budget',
                'delete budget',
                'set ergp',
                'manage ergp',
                'view ergp',
                'raise sick leave',
                'approve leave',
                'approve dta',
                'reject dta',
                'view leave report',
                'show pos dashboard',
                'show crm dashboard',
                'show hrm dashboard',
                'show project dashboard',
                'manage user',
                'create user',
                'edit user',
                'delete user',
                'manage role',
                'create role',
                'edit role',
                'delete role',
                'manage permission',
                'create permission',
                'edit permission',
                'delete permission',
                'manage company settings',
                'manage business settings',
                'manage expense',
                'create expense',
                'edit expense',
                'delete expense',
                'manage invoice',
                'create invoice',
                'edit invoice',
                'delete invoice',
                'show invoice',
                'manage product & service',
                'create product & service',
                'delete product & service',
                'edit product & service',
                'manage constant tax',
                'create constant tax',
                'edit constant tax',
                'delete constant tax',
                'manage constant category',
                'create constant category',
                'edit constant category',
                'delete constant category',
                'manage constant unit',
                'create constant unit',
                'edit constant unit',
                'delete constant unit',
                'manage customer',
                'create customer',
                'edit customer',
                'delete customer',
                'show customer',
                'manage vender',
                'create vender',
                'edit vender',
                'delete vender',
                'show vender',
                'manage bank account',
                'create bank account',
                'edit bank account',
                'delete bank account',
                'manage bank transfer',
                'create bank transfer',
                'edit bank transfer',
                'delete bank transfer',
                'manage revenue',
                'create revenue',
                'edit revenue',
                'delete revenue',
                'manage bill',
                'create bill',
                'edit bill',
                'delete bill',
                'show bill',
                'manage payment',
                'create payment',
                'edit payment',
                'delete payment',
                'delete invoice product',
                'delete bill product',
                'send invoice',
                'create payment invoice',
                'delete payment invoice',
                'send bill',
                'create payment bill',
                'delete payment bill',
                'income report',
                'expense report',
                'income vs expense report',
                'invoice report',
                'bill report',
                'stock report',
                'tax report',
                'loss & profit report',
                'manage transaction',
                'manage order',
                'manage credit note',
                'create credit note',
                'edit credit note',
                'delete credit note',
                'manage debit note',
                'create debit note',
                'edit debit note',
                'delete debit note',
                'duplicate invoice',
                'convert invoice',
                'duplicate bill',
                'manage proposal',
                'create proposal',
                'edit proposal',
                'delete proposal',
                'duplicate proposal',
                'show proposal',
                'send proposal',
                'delete proposal product',
                'manage goal',
                'create goal',
                'edit goal',
                'delete goal',
                'manage assets',
                'create assets',
                'edit assets',
                'delete assets',
                'statement report',
                'manage constant custom field',
                'create constant custom field',
                'edit constant custom field',
                'delete constant custom field',
                'manage chart of account',
                'create chart of account',
                'edit chart of account',
                'delete chart of account',
                'manage journal entry',
                'create journal entry',
                'edit journal entry',
                'delete journal entry',
                'show journal entry',
                'balance sheet report',
                'ledger report',
                'trial balance report',
                'manage client',
                'create client',
                'edit client',
                'delete client',
                'manage lead',
                'create lead',
                'view lead',
                'edit lead',
                'delete lead',
                'move lead',
                'create lead call',
                'edit lead call',
                'delete lead call',
                'create lead email',
                'manage pipeline',
                'create pipeline',
                'edit pipeline',
                'delete pipeline',
                'manage lead stage',
                'create lead stage',
                'edit lead stage',
                'delete lead stage',
                'convert lead to deal',
                'manage source',
                'create source',
                'edit source',
                'delete source',
                'manage label',
                'create label',
                'edit label',
                'delete label',
                'manage deal',
                'create deal',
                'view task',
                'create task',
                'edit task',
                'delete task',
                'edit deal',
                'view deal',
                'delete deal',
                'move deal',
                'create deal call',
                'edit deal call',
                'delete deal call',
                'create deal email',
                'manage stage',
                'create stage',
                'edit stage',
                'delete stage',
                'manage employee',
                'create employee',
                'Upload Employee Document',
                'Manage Employee FIle',
                'Create Employee FIle',
                'view employee',
                'edit employee',
                'delete employee',
                'manage employee profile',
                'show employee profile',
                'manage department',
                'create department',
                'view department',
                'edit department',
                'delete department',
                'manage designation',
                'create designation',
                'view designation',
                'edit designation',
                'delete designation',
                'manage branch',
                'create branch',
                'edit branch',
                'delete branch',
                'manage document type',
                'create document type',
                'edit document type',
                'delete document type',
                'manage document',
                'create document',
                'edit document',
                'manage payslip type',
                'create payslip type',
                'edit payslip type',
                'delete payslip type',
                'create allowance',
                'edit allowance',
                'delete allowance',
                'create commission',
                'edit commission',
                'delete commission',
                'manage allowance option',
                'create allowance option',
                'edit allowance option',
                'delete allowance option',
                'manage loan option',
                'create loan option',
                'edit loan option',
                'delete loan option',
                'manage deduction option',
                'create deduction option',
                'edit deduction option',
                'delete deduction option',
                'create loan',
                'edit loan',
                'delete loan',
                'create saturation deduction',
                'edit saturation deduction',
                'delete saturation deduction',
                'create other payment',
                'edit other payment',
                'delete other payment',
                'create overtime',
                'edit overtime',
                'delete overtime',
                'manage set salary',
                'edit set salary',
                'manage pay slip',
                'create set salary',
                'create pay slip',
                'manage company policy',
                'create company policy',
                'edit company policy',
                'delete document',
                'manage appraisal',
                'create appraisal',
                'edit appraisal',
                'show appraisal',
                'delete appraisal',
                'manage goal tracking',
                'create goal tracking',
                'edit goal tracking',
                'delete goal tracking',
                'manage goal type',
                'create goal type',
                'edit goal type',
                'delete goal type',
                'manage indicator',
                'create indicator',
                'edit indicator',
                'show indicator',
                'delete indicator',
                'manage event',
                'create event',
                'edit event',
                'delete event',
                'manage meeting',
                'create meeting',
                'edit meeting',
                'delete meeting',
                'manage training',
                'create training',
                'edit training',
                'delete training',
                'show training',
                'manage trainer',
                'create trainer',
                'edit trainer',
                'delete trainer',
                'manage training type',
                'create training type',
                'edit training type',
                'delete training type',
                'manage award',
                'create award',
                'edit award',
                'delete award',
                'manage award type',
                'create award type',
                'edit award type',
                'delete award type',
                'manage resignation',
                'create resignation',
                'edit resignation',
                'delete resignation',
                'manage travel',
                'create travel',
                'edit travel',
                'delete travel',
                'manage promotion',
                'create promotion',
                'edit promotion',
                'delete promotion',
                'manage complaint',
                'create complaint',
                'edit complaint',
                'delete complaint',
                'manage warning',
                'create warning',
                'edit warning',
                'delete warning',
                'manage termination',
                'create termination',
                'edit termination',
                'delete termination',
                'manage termination type',
                'create termination type',
                'edit termination type',
                'delete termination type',
                'manage job application',
                'create job application',
                'show job application',
                'delete job application',
                'move job application',
                'add job application skill',
                'add job application note',
                'delete job application note',
                'manage job onBoard',
                'manage job category',
                'create job category',
                'edit job category',
                'delete job category',
                'manage job',
                'create job',
                'edit job',
                'show job',
                'delete job',
                'manage job stage',
                'create job stage',
                'edit job stage',
                'delete job stage',
                'manage jobber application',
                'create jobber application',
                'show jobber application',
                'delete jobber application',
                'move jobber application',
                'add jobber application skill',
                'add jobber application note',
                'delete jobber application note',
                'manage jobber onBoard',
                'manage jobber category',
                'create jobber category',
                'edit jobber category',
                'delete jobber category',
                'manage jobber',
                'create jobber',
                'edit jobber',
                'show jobber',
                'delete jobber',
                'manage jobber stage',
                'create jobber stage',
                'edit jobber stage',
                'delete jobber stage',
                'Manage Competencies',
                'Create Competencies',
                'Edit Competencies',
                'Delete Competencies',
                'manage custom question',
                'create custom question',
                'edit custom question',
                'delete custom question',
                'create interview schedule',
                'edit interview schedule',
                'delete interview schedule',
                'show interview schedule',
                'create estimation',
                'view estimation',
                'edit estimation',
                'delete estimation',
                'edit holiday',
                'create holiday',
                'delete holiday',
                'manage holiday',
                'create overtime',
                'edit overtime',
                'delete overtime',
                'show career',
                'manage transfer',
                'create transfer',
                'edit transfer',
                'delete transfer',
                'manage announcement',
                'create announcement',
                'edit announcement',
                'delete announcement',
                'manage leave',
                'create leave',
                'edit leave',
                'delete leave',
                'manage leave type',
                'create leave type',
                'edit leave type',
                'delete leave type',
                'manage attendance',
                'create attendance',
                'edit attendance',
                'delete attendance',
                'manage report',
                'manage project',
                'create project',
                'view project',
                'edit project',
                'delete project',
                'share project',
                'create milestone',
                'edit milestone',
                'delete milestone',
                'view milestone',
                'view grant chart',
                'manage project stage',
                'create project stage',
                'edit project stage',
                'delete project stage',
                'view timesheet',
                'view expense',
                'manage project task',
                'create project task',
                'edit project task',
                'view project task',
                'delete project task',
                'view activity',
                'view CRM activity',
                'manage project task stage',
                'create project task stage',
                'edit project task stage',
                'delete project task stage',
                'manage timesheet',
                'create timesheet',
                'edit timesheet',
                'manage bug report',
                'create bug report',
                'edit bug report',
                'delete bug report',
                'move bug report',
                'manage bug status',
                'create bug status',
                'edit bug status',
                'delete bug status',
                'manage print settings',
                'manage company plan',
                'buy plan',
                'copy invoice',
                'manage plan',
                'manage form builder',
                'create form builder',
                'edit form builder',
                'delete form builder',
                'manage performance type',
                'create performance type',
                'edit performance type',
                'delete performance type',
                'manage form field',
                'create form field',
                'edit form field',
                'delete form field',
                'view form response',
                'manage budget plan',
                'create budget plan',
                'edit budget plan',
                'delete budget plan',
                'view budget plan',
                'manage warehouse',
                'create warehouse',
                'edit warehouse',
                'show warehouse',
                'delete warehouse',
                'manage purchase',
                'create purchase',
                'edit purchase',
                'show purchase',
                'delete purchase',
                'send purchase',
                'create payment purchase',
                'delete payment purchase',
                'manage pos',
                'manage contract type',
                'create contract type',
                'edit contract type',
                'delete contract type',
                'manage contract',
                'create contract',
                'edit contract',
                'delete contract',
                'show contract',
                'create barcode',
                'create webhook',
                'edit webhook',
                'delete webhook',
                'manage permission',
                'manage employee',
                'create employee',
                'edit employee',
                'delete employee',
                'create unit document',
                'create department document',
                'create unit folder',
                'create department folder',
            ],

            'user' => [
                'share document',
                'archive document',
                'create folder',
                'create document',
                'view unit documents',
                'view unit folders',
                'show invoice',
                'show proposal',
                'show profile',
                'request SRN',
                'view department documents',
                'view department folders',

            ],
            'director' => [
                'create folder',
                'view department folders',
                'view unit folders',
                'rename folder',
                'delete folder',
                'create document',
                'view department documents',
                'view department folders',
                'view unit documents',
                'share document',
                'rename document',
                'archive document',
                 'manage report',
                'raise query',
                'report view',
                'director approve',
                'director approve SRN',
                'approve as director',
                'manage requisition',
                'manage attendance report',
                'manage attendance',
                'create attendance',
                'set budget',
                'view budget',
                'edit budget',
                'delete budget',
                'approve leave',
                'view leave report',
                'create budget plan',
                'show invoice',
                'show proposal',
                'show profile',
                'manage client dashboard',
                'create unit document',
                'create department document',
                'create unit folder',
                'create department folder',
                'view department documents',
                'view department folders',
                'create unit document',
                'create unit folder',
            ],
            'unit head' => [
                'create folder',
                'view unit folders',
                'rename folder',
                'delete folder',
                'create document',
                'view unit documents',
                'share document',
                'rename document',
                'archive document',
                'unit head approve',
                'raise query',
                'approve as pv',
                'approve leave',
                'manage leave',
                'approve dta',
                'reject dta',
                'view leave report',
                'show unithead dashboard',
                'view department documents',
                'view department folders',
                'create unit document',
                'create unit folder',
                'view department documents',
                'view department folders',
                'create unit document',
                'create unit folder',
            ],
            'store keeper' => [
                'view item supply',
                'request purchase requisition',
                'share document',
                'archive document',
                'create folder',
                'create document',
                'view unit documents',
                'view unit folders',
                'store approve SRN',
                'approve as audit',
                'manage product & service',
                'manage warehouse',
                'manage purchase',
                'manage pos',
                'manage warehouse',
                'show unithead dashboard',
                'view department documents',
                'view department folders',
                'view department documents',
                'view department folders',
                'view unit documents',
                'view unit folders'
            ],
            'DG' => [
                 'dg approve',
                 'raise query',
                 'approve as dg',
                 'manage requisition',
                 'manage project',
                 'approve budget',
                 'reject budget',
                 'view budget',
                 'view contract',
                 'approve payment',
                 'view payment history',
                 'view contract value',
                 'print voucher',
                 'comment on contract',
                 'manage contract',
                 'view recommended payment',
                 'view department documents',
                 'view department folders',
                 'view unit documents',
                 'view unit folders',
            ],
            "DG/CE's Personal Assistant" => [
                 'manage requisition',
                 'manage project',
                 'reject budget',
                 'view budget',
                 'view contract',
                 'view payment history',
                 'view contract value',
                 'print voucher',
                 'comment on contract',
                 'manage contract',
                 'view department documents',
                 'view department folders',
                 'view unit documents',
                 'view unit folders',
            ],
            "DG/CE's Admin Officer" => [
                 'manage requisition',
                 'manage project',
                 'reject budget',
                 'view budget',
                 'view contract',
                 'view payment history',
                 'view contract value',
                 'print voucher',
                 'comment on contract',
                 'manage contract',
                 'view department documents',
                 'view department folders',
                 'view unit documents',
                 'view unit folders',
            ],
            "DG/CE's Secretary" => [
                 'manage requisition',
                 'manage project',
                 'reject budget',
                 'view budget',
                 'view contract',
                 'view payment history',
                 'view contract value',
                 'print voucher',
                 'comment on contract',
                 'manage contract',
                 'view department documents',
                 'view department folders',
                 'view unit documents',
                 'view unit folders',
            ],
            "DG/CE's Special Assistant" => [
                 'manage requisition',
                 'manage project',
                 'reject budget',
                 'view budget',
                 'view contract',
                 'view payment history',
                 'view contract value',
                 'print voucher',
                 'comment on contract',
                 'manage contract',
                 'view department documents',
                 'view department folders',
                 'view unit documents',
                 'view unit folders',
            ],
            'supervisor' => [
                'create folder',
                'create document',
                'view unit documents',
                'view unit folders',
                'share document',
                'archive document',
                'raise query',
                'approve as bursar',
                'approve leave',
                'approve dta',
                'reject dta',
                'show invoice',
                'show proposal',
                'show profile',
                'manage client dashboard',
                'manage bug report',
                'create bug report',
                'edit bug report',
                'delete bug report',
                'move bug report',
                'view deal',
                'manage deal',
                'manage project',
                'view project',
                'view grant chart',
                'view timesheet',
                'manage timesheet',
                'manage project task',
                'create project task',
                'edit project task',
                'view project task',
                'delete project task',
                'view activity',
                'view task',
                'manage pipeline',
                'manage lead stage',
                'manage label',
                'manage source',
                'move deal',
                'manage stage',
                'manage contract',
                'show contract',
                'view department documents',
                'view department folders',
            ],
            'liaison officer' => [
                'share document',
                'archive document',
                'create folder',
                'create document',
                'view unit documents',
                'view unit folders',
                'liaison approve',
                'raise query',
                'liaison approve SRN',
                'approve leave',
                'view leave report',
                'create budget plan',
                'show invoice',
                'show proposal',
                'show profile',
                'manage client dashboard',
                'view department documents',
                'view department folders',
            ],
            'accountant' => [
                'share document',
                'archive document',
                'create folder',
                'create document',
                'view unit documents',
                'view unit folders',
                'final account approve',
                'report view',
                'director approve',
                'bursar approve SRN',
                'approve as cash office',
                'set budget',
                'manage budget',
                'approve budget',
                'view budget',
                'edit budget',
                'delete budget',
                'set ergp',
                'manage ergp',
                'view ergp',
                'show account dashboard',
                'approve dta',
                'reject dta',
                'manage purchase',
                'create barcode',
                'manage pos',
                'manage expense',
                'create expense',
                'edit expense',
                'delete expense',
                'manage invoice',
                'create invoice',
                'edit invoice',
                'delete invoice',
                'show invoice',
                'convert invoice',
                'manage product & service',
                'create product & service',
                'delete product & service',
                'edit product & service',
                'manage constant tax',
                'create constant tax',
                'edit constant tax',
                'delete constant tax',
                'manage constant category',
                'create constant category',
                'edit constant category',
                'delete constant category',
                'manage constant unit',
                'create constant unit',
                'edit constant unit',
                'delete constant unit',
                'manage customer',
                'create customer',
                'edit customer',
                'delete customer',
                'show customer',
                'manage vender',
                'create vender',
                'edit vender',
                'delete vender',
                'show vender',
                'manage bank account',
                'create bank account',
                'edit bank account',
                'delete bank account',
                'manage bank transfer',
                'create bank transfer',
                'edit bank transfer',
                'delete bank transfer',
                'manage revenue',
                'create revenue',
                'edit revenue',
                'delete revenue',
                'manage bill',
                'create bill',
                'edit bill',
                'delete bill',
                'show bill',
                'manage payment',
                'create payment',
                'edit payment',
                'delete payment',
                'delete invoice product',
                'delete bill product',
                'send invoice',
                'create payment invoice',
                'delete payment invoice',
                'send bill',
                'create payment bill',
                'delete payment bill',
                'income report',
                'expense report',
                'income vs expense report',
                'invoice report',
                'bill report',
                'stock report',
                'tax report',
                'loss & profit report',
                'manage transaction',
                'manage credit note',
                'create credit note',
                'edit credit note',
                'delete credit note',
                'manage debit note',
                'create debit note',
                'edit debit note',
                'delete debit note',
                'manage proposal',
                'create proposal',
                'edit proposal',
                'delete proposal',
                'duplicate proposal',
                'send proposal',
                'show proposal',
                'delete proposal product',
                'manage goal',
                'create goal',
                'edit goal',
                'delete goal',
                'manage assets',
                'create assets',
                'edit assets',
                'delete assets',
                'statement report',
                'manage constant custom field',
                'create constant custom field',
                'edit constant custom field',
                'delete constant custom field',
                'manage chart of account',
                'create chart of account',
                'edit chart of account',
                'delete chart of account',
                'manage journal entry',
                'create journal entry',
                'edit journal entry',
                'delete journal entry',
                'show journal entry',
                'balance sheet report',
                'ledger report',
                'trial balance report',
                'manage print settings',
                'manage budget plan',
                'create budget plan',
                'edit budget plan',
                'delete budget plan',
                'view budget plan',
                'create barcode',
                'view department documents',
                'view department folders',
            ],
            'deputy bursar' => [
                'show account dashboard',
                'manage ergp',
                'view ergp',
                'view department documents',
                'view department folders',
                'view unit documents',
                'view unit folders',
            ],
            'registrar' => [
                'create employee',
                'manage employee',
                'manage trainer',
                'create trainer',
                'edit trainer',
                'manage training',
                'create training',
                'manage training type',
                'create training type',
                'edit meeting',
                'create meeting',
                'manage meeting',
                'delete meeting',
                'create announcement',
                'manage announcement',
                'edit announcement',
                'share document',
                'archive document',
                'create folder',
                'create document',
                'view unit documents',
                'view unit folders',
                'assign query',
                'manage attendance',
                'manage attendance report',
                'create attendance',
                'view leave report',
                'show hrm dashboard',
                'manage employee',
                'manage leave',
                'manage indicator',
                'manage appraisal',
                'manage goal tracking',
                'manage job',
                'create job',
                'manage job application',
                'manage custom question',
                'show interview schedule',
                'manage award',
                'manage transfer',
                'manage resignation',
                'manage travel',
                'manage promotion',
                'manage complaint',
                'manage warning',
                'manage termination',
                'manage holiday',
                'manage event',
                'manage assets',
                'manage document',
                'manage company policy',
                'show career',
                'manage report',
                'manage user',
                'manage role',
                'manage client',
                'view department documents',
                'view department folders',
            ],
            'assistant registrar' => [
                'share document',
                'archive document',
                'create folder',
                'create document',
                'view unit documents',
                'view unit folders',
                'assign query',
                'manage attendance',
                'manage attendance report',
                'create attendance',
                'view leave report',
                'show hrm dashboard',
                'manage employee',
                'manage leave',
                'manage indicator',
                'manage appraisal',
                'manage goal tracking',
                'manage training',
                'manage job',
                'create job',
                'manage job application',
                'manage custom question',
                'show interview schedule',
                'manage award',
                'manage transfer',
                'manage resignation',
                'manage travel',
                'manage promotion',
                'manage complaint',
                'manage warning',
                'manage termination',
                'manage announcement',
                'manage holiday',
                'manage event',
                'manage meeting',
                'manage assets',
                'manage document',
                'manage company policy',
                'show career',
                'manage report',
                'manage user',
                'manage role',
                'manage client',
                'view department documents',
                'view department folders',
            ],

            'contractor' => [
                'view project',
            ],

        ];

        // Get the permissions for the user type
        $userPermissions = $permissions[$userType] ?? [];

        // Assign the permissions to the role
        foreach ($userPermissions as $permissionName) {
            $permission = Permission::firstOrCreate(['name' => $permissionName]); // Create the permission if it doesn't exist
            if (!$role->hasPermissionTo($permission)) {
                $role->givePermissionTo($permission);
            }
        }
    }
}

function createNotification($userId, $title, $body, $link = null)
{
    InternalNotification::create([
        'user_id' => $userId,
        'title' => $title,
        'body' => $body,
        'link' => $link,
    ]);
}

function markAsRead($notificationId)
{
    $notification = InternalNotification::where('id', $notificationId)
        ->where('user_id', auth()->id())
        ->first();

    if ($notification) {
        $notification->update(['is_read' => true]);
        return true;
    }

    return false;
}

function markAllAsRead()
{
    return InternalNotification::where('user_id', auth()->id())
        ->where('is_read', false)
        ->update(['is_read' => true]);
}

if (!function_exists('getDepartmentPermissions')) {
    function getDepartmentPermissions($departmentName)
    {
        $permissions = [
            'Bursary Department' => [
                    'show reports',
                    'statement report',
                    'invoice report',
                    'bill report',
                    'stock report',
                    'loss & profit report',
                    'manage transaction',
                    'income report',
                    'expense report',
                    'income vs expense report',
                    'tax report',
                    'show banking',
                    'show voucher',
                    'show purchases',
                    'show double entry',
                    'show chart of account',
                    'show journal',
                    'show ledger',
                    'show balance sheet',
                    'show profit and loss',
                    'show trial balance',
                    'trial balance report',
                    'manage proposal',
                    'manage customer',
                    'show budget planner',
                    'show financial goal',
                    'show accounting setup',
                    'show print setup',
                    'manage journal entry',
                    'create journal entry',
                    'create invoice',
                    'show journal entry',
                    'edit journal entry',
                    'delete journal entry',
                    'manage chart of account',
                    'create chart of account',
                    'ledger report',
                    'edit chart of account',
                    'delete chart of account',
                    'trial balance report',
                    'manage report',
                    'bill report',
                    'income vs expense report'

                ],
            'Registry Department' => [
                'create employee',
                'manage employee',
                'create meeting',
                'manage meeting',
                'create announcement',
                'manage announcement',
                'show hrm dashboard',
                'manage payment',
                'manage report',
                'manage training',
                'manage trainer',
                'manage event',
                'manage job',
                'create job',
                'manage job application',
                'manage custom question',
                'show interview schedule',
                'manage award',
                'manage transfer',
                'manage assets',
                'manage company policy',
                'manage trainer',
                'create trainer',
                'manage training',
                'create training',
                'manage training type',
                'create training type',
            ],
        ];

        // Return the permissions for the given department or an empty array
        return $permissions[$departmentName] ?? [];
    }
}

if (!function_exists('getUnitPermissions')) {
    function getUnitPermissions($unitName)
    {
        $permissions = [
            'Physical Planing Unit' => [
                'manage project',
                'manage contract',
                'create project',
            ],
            'Procurement Unit' => [
                'manage project',
                'manage client',
                'manage contract',
                'create project',
            ],
            'Stores' => [
                'manage stock',
                'view stock',
                'manage warehouse',
            ],
        ];

        // Return the permissions for the given unit or an empty array if not found
        return $permissions[$unitName] ?? [];
    }
}
